# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Montana Climate Office
email: colin.brust@mso.umt.edu
description: >- # this means to ignore newlines until "baseurl:"
  The official website of the Montana Climate Office. 
url: https://climate.umt.edu # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
# baseurl: /mco-website # the subpath of your site, e.g. "/blog"
repository: "mt-climate-office/mco-website" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
github_username: mt-climate-office
minimal_mistakes_skin: "default"
search: true
logo: "/assets/images/MCO_logo_icon_only.png"
masthead_title: "Montana Climate Office"
locale: "en-US"
contact: >-
  Montana Climate Office <br>
  Montana Forest & Conservation Experiment Station <br>
  University of Montana <br>
  32 Campus Drive <br>
  Missoula, MT 59812 <br>
  Phone: (406) 243-6793 <br>
  <a href="mailto:state.climatologist@umontana.edu">state.climatologist@umontana.edu</a> <br>

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-get-json

author:
  name   : "Colin Brust"
  avatar : "/assets/images/brust.jpg"
  bio    : "Colin develops and maintains the API, dashboard and database for the Montana Mesonet."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://colinbrust.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/colin_brust"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/colinbrust"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mt-climate-office"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:state.climatologist@umontana.edu"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mt_climate"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

lunr:
  search_within_pages: false
#   search_within_pages: true

jekyll_get_json:
  - data: stations
    json: 'https://mesonet.climate.umt.edu/api/v2/stations?type=json'

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-96RBQYREG6"
    anonymize_ip: false # default